apiVersion: apps/v1
kind: Deployment
metadata:
  name: ultron
  namespace: ultron
  labels:
    app: ultron
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ultron
  template:
    metadata:
      labels:
        app: ultron
    spec:
      containers:
        - name: ultron
          image: docker.io/bluecipherpub/ultron:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: docker-hub-hackathon2022

