name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER
      IMAGE_NAME: bluecipherpub/ultron

    strategy:
      matrix:
        #node-version: [12.x, 14.x, 16.x]
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - run: |
        sed -e "s, APPIMAGE, 'docker.io/bluecipherpub/ultron/${{ env.IMAGE_TAG }}',g" resources/deployment.yml
        cd /home/runner/work/ultron/ultron/resources
        cat deployment.yml
        
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Release docker image version
        
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    
    
 #   - uses: actions/checkout@v2
  #  - run: echo "123" > resources.txt
  #  - run: pwd
   # - run: ls -lrt
   # - run: cat resources.txt
   # - run: git status
    #- run: git add resources.txt
    #- run: git commit -m 'txt update'
   # - run: git push origin main
   

    - name: Build Docker Image
      run:
        docker build --tag docker.io/bluecipherpub/ultron:${{ env.IMAGE_TAG }} .

        
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
          image-ref: 'docker.io/bluecipherpub/ultron:${{ env.IMAGE_TAG }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'library'
          severity: 'CRITICAL,HIGH'

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
  
    - name: Push Image to Docker Hub
      run:
        docker push docker.io/bluecipherpub/ultron:${{ env.IMAGE_TAG }}
    
    - name: updating release
    - uses: actions/checkout@v2
    - run: |
        sed -e "s, APPIMAGE, 'docker.io/bluecipherpub/ultron/${{ env.IMAGE_TAG }}',g" resources/deployment.yml
        cd /home/runner/work/ultron/ultron/resources
        cat deployment.yml
        
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Release docker image version


    
