name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER

    strategy:
      matrix:
        #node-version: [12.x, 14.x, 16.x]
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    

    - name: Build Docker Image
      run:
        docker build --tag docker.io/bluecipherpub/ultron:${{ env.IMAGE_TAG }} .

        
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
          image-ref: 'docker.io/bluecipherpub/ultron:${{ env.IMAGE_TAG }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'library'
          severity: 'CRITICAL,HIGH'
    - uses: cschleiden/replace-tokens@v1
      with:
        files: '["resources/*.yaml"]'
        tokenPrefix: __ # optional, default is #{
        tokenSuffix: __ # optional, default is }#
      env:
        DOCKER_REPOSITORY: docker.io/bluecipherpub/
        IMAGE_NAME: ultron
        IMAGE_TAG: ${{ env.IMAGE_TAG }}


    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
  
    - name: Push Image to Docker Hub
      run:
        docker push docker.io/bluecipherpub/ultron:${{ env.IMAGE_TAG }}

    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
          find: "ultron:"
          replace: "ultron:${{ env.IMAGE_TAG }}"
          regex: true
          include : "../resources/**"
